
version: '2'

services:

 guacd:
  hostname: guacd
  image: danielguerra/guacamole-guacd

 guadb:
  hostname: guadb
  image: danielguerra/guacamole-db
  environment:
    - MYSQL_ROOT_PASSWORD=mypass

 guaweb:
  image: danielguerra/guacamole-webserver
  links:
    - guacd
    - "guadb:db"
    - xrdp
 sshd:
  image: danielguerra/alpine-sshdx
  links:
   - guaweb
   - xrdp
  volumes:
   - ssh-keys:/root/.ssh
   - user-data:/home/alpine/rdpuser
  ports:
   - "22222:22"

 xrdp:
  image: danielguerra/alpine-xfce4-xrdp
  hostname: xrdp
  volumes:
  -  user-data:/home/alpine

volumes:
 ssh-keys:
 user-data:
