guacd:
  hostname: guacd
  image: danielguerra/guacamole-guacd

guadb:
  hostname: guadb
  image: danielguerra/guacamole-db
  environment:
    - MYSQL_ROOT_PASSWORD=mypass

guaweb:
  image: danielguerra/guacamole-webserver
  links:
    - guacd
    - "guadb:db"
    - soulseek
  ports:
   - "8080:8080"

soulseek:
 image: danielguerra/soulseek
 hostname: soulseek
 ports:
 - "5900:5900"
