guacd:
  hostname: guacd
  image: danielguerra/guacamole-guacd

guadb:
  hostname: guadb
  image: danielguerra/guacamole-db
  environment:
    - MYSQL_ROOT_PASSWORD=mypass

guaweb:
  image: danielguerra/guacamole-webserver
  links:
    - guacd
    - "guadb:db"

sshd:
  image: danielguerra/alpine-sshdx
  links:
   - guacaweb
   - android-studio
  ports:
   - "22"

android-studio:
 image: danielguerra/android-studio
 hostname: android-studio
